<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 2</h2></center>

## NumPy Array

In [ ]:
# Import NumPy library
import numpy as np

In [ ]:
# Define NumPy Array from a list
my_np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
my_np_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create a list, and cast it to NumPy Array
# Notice it changes all the items to the same data type
fahrenheit_temp = [100.4, 95, 120, 58.4]

fahrenheit_np_array = np.array(fahrenheit_temp)
fahrenheit_np_array

array([100.4,  95. , 120. ,  58.4])

In [ ]:
# Calculation will be performed on all members of the NumPy array
celsius = (fahrenheit_np_array - 32) * 5 / 9
celsius

array([38.        , 35.        , 48.88888889, 14.66666667])

In [ ]:
# Slicing - print only first 2 numbers
print (my_np_array[0:2])

[1 2]


In [ ]:
# Slicing - print in reverse order
print (my_np_array[::-1])

[9 8 7 6 5 4 3 2 1]


In [ ]:
# Returns the boolean result of the condition
my_np_array > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [ ]:
# Print items for which the condition is true
my_np_array [  my_np_array > 4     ]

# mask = my_np_array > 4
# my_np_array [mask]

array([5, 6, 7, 8, 9])

In [ ]:
# 2 conditions with and operator
my_np_array [  (my_np_array > 4) & (my_np_array < 8)     ]

# mask1 = my_np_array > 4
# mask2 = my_np_array < 8
# my_np_array [mask1 & mask2]

array([5, 6, 7])

In [ ]:
# 2 conditions with or operator
# my_np_array [(my_np_array < 3) | (my_np_array > 7)]
mask1 = my_np_array < 3
mask2 = my_np_array > 7

my_np_array [mask1 | mask2]

array([1, 2, 8, 9])

In [ ]:
# returns the total number of elements
my_np_array.size

9

[link text](https://)

## NumPy Matrix

In [ ]:
# create 2D matrix
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print (my_matrix)

my_np_matrix = np.matrix (my_matrix)
my_np_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Example - Appartment data
#                               [app no, sqm, floor, rooms, Toilets]
appartment_np_array = np.array ([[1000,  150,   6,     7,      3 ],
                                 [1001,  134,   5,     3,      2 ],
                                 [1002,   80,   4,     1,      2 ]  ] )

appartment_np_array

array([[1000,  150,    6,    7,    3],
       [1001,  134,    5,    3,    2],
       [1002,   80,    4,    1,    2]])

In [ ]:
# What is the square meter of apartment 1002?
appartment_np_array[2][1]
# another option
appartment_np_array[2,1]

80

In [ ]:
# How many bathrooms are there in apartment 1001?
appartment_np_array[1][4]

2

In [ ]:
# After renovating apartment 1001, they only have one bathroom left
# Please update the data

appartment_np_array[1][4] = 1

appartment_np_array

array([[1000,  150,    6,    7,    3],
       [1001,  134,    5,    3,    1],
       [1002,   80,    4,    1,    2]])

## Array / Matrix Attributes

Attributes return information about the object.

Attributes do not require parentheses

In [ ]:
# Check dimensions number
appartment_np_array.ndim

2

In [ ]:
# Check shape, returns (number_of_rows, number_of_columns)
appartment_np_array.shape

(3, 5)

In [ ]:
# How many total items
appartment_np_array.size

15

In [ ]:
# Data type of the items
appartment_np_array.dtype

dtype('int32')

## Numpy methods

#### np.arange (start, stop, step)

Return evenly spaced values within a given interval in NumPy array

In [ ]:
# np.arange (start, stop, step)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# NumPy Array - steps of float cannot be done in regular range()
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

#### linspace

Return evenly spaced numbers over a specified interval

In [ ]:
# np.linspace (start, stop, how_many_items_to_return)
np.linspace (0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

#### Random - rand

Return a sample (or samples) from the uniform distribution over [0, 1)

In [ ]:
# np.random.rand (d0, d1, ... dn)
# Random values in a given shape

np.random.rand (3)

array([0.00733459, 0.98414148, 0.64392603])

#### Random - randn

Return a sample (or samples) from the standard normal distribution

In [ ]:
# np.random.randn (d0, d1, ... dn)

np.random.randn (3,4)

array([[ 0.18779199, -1.10154561, -1.91573557, -1.26967943],
       [ 0.74527083, -1.10944829, -1.06651525,  0.93472478],
       [-0.20341115,  1.19259358,  0.09553359, -0.0968954 ]])

#### Random - randint

Return random integers from low (inclusive) to high (exclusive)

In [ ]:
# np.random.randint (low, high, no_of_items)

arr = np.random.randint (0, 10, 8)
arr

array([7, 0, 3, 5, 6, 6, 4, 3])

## Array / Matrix methods

In [ ]:
# Return the maximum along a given axis
arr.max()

7

In [ ]:
# Return indices of the maximum values along the given axis
arr.argmax ()

0

In [ ]:
# Return the minimum along a given axis
arr.min ()

0

In [ ]:
# Return indices of the minimum values along the given axis
arr.argmin()

1

In [ ]:
# Sort an array in-place
arr.sort()
arr

array([0, 3, 3, 4, 5, 6, 6, 7])

#### Shape and axis

<img height="200" src="arr_shape.png" width="500" alt="Hands on" id="prc_time" title="Data Analyst Course">

In [ ]:
# creat matrix from random numbers between 0-10
# matrix shape: 3 rows, 4 columns
mtx = np.random.randint (0, 11, (3,4))
mtx


array([[ 8,  8,  8,  0],
       [10,  5,  8,  9],
       [ 9,  5,  3,  4]])

In [ ]:
# axis=0 >> within columns,
# axis=1 >> within rows
mtx.sum(axis=0)

array([ 2, 13, 16,  9])

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Class Practice 2.1</h1></center>

1. Define a matrix in a shape (4,5), whose values will be random between 1 and 10 inclusive.


2. Print the second column of the matrix


3. Print values greater than 4


4. What is the highest value in the matrix?


5. What is the total sum of the numbers of the matrix members?

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Home Practice 2</h1></center>

1. Define a matrix with 5 rows and 3 columns, whose values will be from the standard normal distribution


2. Multiply the values in the third column by 2


3. What is the minimum value in the matrix?


4. What is the mean value?


5. Show only the values that are bigger then the mean value

=========================================================================================

#### Pactice 2.1 - Solution
1. Define a matrix in a shape (4,5), whose values will be random between 1 and 10 inclusive.


2. Print the second column of the matrix


3. Print values greater than 4


4. What is the highest value in the matrix?


5. What is the total sum of the numbers of the matrix members?

In [ ]:
# 1
my_mtx = np.random.randint (1, 11, (4,5))
my_mtx

array([[ 9, 10, 10,  7,  8],
       [ 2,  1,  7,  5,  5],
       [ 6,  6,  6,  4,  8],
       [ 7,  7,  4,  4, 10]])

In [ ]:
# 2
my_mtx[:,1]

array([10,  1,  6,  7])

In [ ]:
# 3
mask = my_mtx > 4
my_mtx [mask]

array([ 9, 10, 10,  7,  8,  7,  5,  5,  6,  6,  6,  8,  7,  7, 10])

In [ ]:
# 4
my_mtx.max()

10

In [ ]:
# 5
my_mtx.sum()

126